### ISSUE TITLE
Release to VSCode Marketplace

### ISSUE THREAD

**Issue by glc-mvion** [about-code/vscode-theme-adapted#1]
This would be cool to install your theme from the marketplace !

If you need some help, I would be happy to fork your repo and try to set up a Travis CI pipeline for you :smiley:

**Comment by about-code** [comment]
Hello @MattMattV. 

Nice to hear you like the theme and thank you for your support offer. Maybe Travis CI would be a bit over the top. I am currently not planning for very frequent updates and the VSCode UI is pretty stable. I think command-line `vsce` would also do the trick. But I have to replace the logo SVGs in the VSIX before being able to publish the theme with `vsce`.

Just in case you didn't notice, you can download a VSIX from the releases page and install the theme locally.

**Comment by glc-mvion** [comment]
The point with Travis (or any CI system) is that, even of you do not
release often, the whole process is automated ans painless, so you can
focus on other things or anything else ! (:

Le ven. 29 juin 2018 à 20:02, Andreas Martin <notifications@github.com> a
écrit :

**Comment by about-code** [comment]
@MattMattV You can now download the theme as version 1.0.2 from the [marketplace](https://marketplace.visualstudio.com/items?itemName=about-code.vscode-theme-adapted).

I would like to dismiss your proposal of using a travis CI pipeline. I use CI systems myself, every day. But `vsce` is easy enough for me to use for this project and it has the advantage of not requiring me to expose my access keys to an external entity (travis-ci.org).

Anyways, I like nice people offering help, so thank you once again.
