### ISSUE TITLE
Indent guides lack colouring

### ISSUE THREAD

**Issue by orangecoloured** [about-code/vscode-theme-adapted#2]
As the title says there are no colours assigned to different indentation guides. They all look the same.

A quick way to check it is to have several levels of indentation on screen, place cursor on one of those levels and start switching themes. You'll see how other built-in themes highlight active/inactive guides with different colours.

**Comment by about-code** [comment]
Thank you for your report. I will look into it.

**Comment by about-code** [comment]
Closed in 7344222b73a34a5364a900e532b2137023ece56f
