### ISSUE TITLE
Request new color variation

### ISSUE THREAD

**Issue by mnabila** [about-code/vscode-theme-adapted#3]
can you add color variations on syntax higlinter like monokai pro (filter spectrume)
please :) :+1: :+1:

**Comment by about-code** [comment]
Sorry @nabil48 but I can't do so. The [Monokai Pro License](https://marketplace.visualstudio.com/items/monokai.theme-monokai-pro-vscode/license) is a commercial license which doesn't allow redistribution of monokai pro nor derivates of it. So I can't take its syntax theme and incorporate it into vscode-theme-adapted.
